# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node-version }} and ${{ matrix.os }}

    runs-on: [ubuntu-latest]
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install libxi-dev
        run: sudo apt-get install libxi-dev

      - name: Install node-gyp
        run: npm install -g node-gyp

      - name: Install dependencies
        run: npm install --force

      - name: Rebuild packages
        run: node-gyp rebuild

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build
