# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node-version }} and ${{ matrix.os }}

    runs-on: [ubuntu-latest]
    timeout-minutes: 20
    # runs-on: [ubuntu-latest, windows-latest, macOS-latest]

    strategy:
      matrix:
        node-version: [15.x, 16.x]
        os: [ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # - name: pkg-config --list-all | grep xi
      #   run: pkg-config --list-all | grep xi
      - name: Installing libxi-dev
        run: sudo apt-get install libxi-dev
      # - name: Set PKG_CONFIG_PATH
      #   run: export PKG_CONFIG_PATH="/path/to/xi.pc:$PKG_CONFIG_PATH"

      - name: Install deps and build (with cache)
        run: npm i --force

      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test --ci --coverage --maxWorkers=2
      - name: Build
        run: npm run build
